services:
  cassandra-node1:
    image: cassandra:5.0
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra-node1
    networks: [net]
    volumes:
      - cassandra-node1-data:/var/lib/cassandra

  cassandra-node2:
    image: cassandra:5.0
    container_name: cassandra-node2
    depends_on: [cassandra-node1]
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    networks: [net]
    volumes:
      - cassandra-node2-data:/var/lib/cassandra

  cassandra-node3:
    image: cassandra:5.0
    container_name: cassandra-node3
    depends_on: [cassandra-node1]
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    networks: [net]
    volumes:
      - cassandra-node3-data:/var/lib/cassandra

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks: [net]

  app:
    build: .
    environment:
      DATABASE_URL: postgres://yugabyte:yugabyte@${COMPOSE_PROJECT_NAME}-yb-1:5433/yugabyte?sslmode=disable
      KAFKA_BROKER: "broker:9092"
    depends_on: [broker, cassandra-node1]
    deploy:
      replicas: 4
    networks: [net]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [app]
    networks: [net]

networks:
  net:

volumes:
  cassandra-node1-data:
  cassandra-node2-data:
  cassandra-node3-data:
